### ISSUE TITLE
Unable to download icons

### ISSUE THREAD

**Issue by tomasconnor** [eucalyptuss/ucreate-icons#28]
`Access to fetch at 'https://api-ikonate.herokuapp.com/api/download_svgs_v2' from origin 'https://ikonate.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
rollbar.min.js:2          POST https://api-ikonate.herokuapp.com/api/download_svgs_v2 net::ERR_FAILED
(anonymous) @ rollbar.min.js:2
value @ main.2ba3ff5a.js:1
onClick @ main.2ba3ff5a.js:1
o @ main.2ba3ff5a.js:1
invokeGuardedCallback @ main.2ba3ff5a.js:1
invokeGuardedCallbackAndCatchFirstError @ main.2ba3ff5a.js:1
u @ main.2ba3ff5a.js:1
d @ main.2ba3ff5a.js:1
m @ main.2ba3ff5a.js:1
p @ main.2ba3ff5a.js:1
v @ main.2ba3ff5a.js:1
y @ main.2ba3ff5a.js:1
ze @ main.2ba3ff5a.js:1
gr @ main.2ba3ff5a.js:1
J @ main.2ba3ff5a.js:1
Ve @ main.2ba3ff5a.js:1
br @ main.2ba3ff5a.js:1
He @ main.2ba3ff5a.js:1
o._rollbar_wrapped.o._rollbar_wrapped @ (index):1
rollbar.min.js:2 TypeError: Failed to fetch
    at rollbar.min.js:2:23724
    at t.value (main.2ba3ff5a.js:1:168289)
    at onClick (main.2ba3ff5a.js:1:167822)
    at Object.o (main.2ba3ff5a.js:1:42450)
    at Object.invokeGuardedCallback (main.2ba3ff5a.js:1:108137)
    at Object.invokeGuardedCallbackAndCatchFirstError (main.2ba3ff5a.js:1:108254)
    at u (main.2ba3ff5a.js:1:43379)
    at d (main.2ba3ff5a.js:1:43847)
    at m (main.2ba3ff5a.js:1:44004)
    at p (main.2ba3ff5a.js:1:43666)`

**Comment by mezod** [comment]
still occurring

**Comment by ari-curtis** [comment]
still occurring
